#!/usr/bin/env python 

"""
Manipulation of regular and context free languages.
"""


class GenCFL(object):
    """Random string generation from the language generated by input grammar.
    """

class RegexToCFG(object):
    """Conversion of basic REs to their corresponding CFGs.
    """

    RE_GRAMMAR = nltk.grammar.parse_cfg("""
        """)

    

